service: fireeye-hackathon-2020
provider:
  name: aws
  profile: delta12-ops-admin
  runtime: nodejs10.x
  stage: dev
  region: us-east-2
  memorySize: 256
functions:
  app:
    handler: app/app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
